name: Semgrep
on: 
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["master", "main"]
  schedule:
    - cron: '12 15 * * *'
jobs:
  semgrep:
    name: semgrep/ci 
    runs-on: ubuntu-latest
    container:
      image: bbonser/llm-agent:main
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}